### PR TITLE
Turn Executor into a ContextManager

### PR DESCRIPTION
**Pull request by felixdivo**
Similar to #1117, but for `rclpy.executors.Executor`.

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]
lgtm

**Comment by fujitatomoya** [comment]
@sloretz can you take a look when you have time?

**Comment by felixdivo** [comment]
Same as: https://github.com/ros2/rclpy/pull/1117#issuecomment-1528771172

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18638/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13168/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19368/)

**Comment by clalancette** [comment]
CI again:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18658/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13186/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19386/)

**Pull request merged**
