### PR TITLE
Deprecate verbose qos policy value names

### PR DESCRIPTION
**Pull request by ivanpauno**
Deprecate the verbose versions (e.g. `rclpy.qos.HistoryPolicy.RMW_QOS_POLICY_HISTORY_KEEP_LAST`) in favor of the less verbose versions (e.g. `rclpy.qos.HistoryPolicy.KEEP_LAST`), so we can remove the verbose version in a future.

### CODE REVIEW

**Comment by ivanpauno** [comment]
@ros-pull-request-builder retest this please

**Comment by ivanpauno** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12880/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7835/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10597/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12823/)

**Review by jacobperron — APPROVED** [review]
LGTM with green CI

**Comment by ivanpauno** [comment]
Checking that the demo_nodes_cpp linter errors are actually fixed:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12890/)

**Comment by ivanpauno** [comment]
@ros-pull-request-builder retest this please

**Pull request merged**
