### PR TITLE
Improve static typings

### PR DESCRIPTION
**Pull request by mateusz-lichota**
As per issue #976 , this PR aims to improve the statics typings of rclpy.

### CODE REVIEW

**Comment by clalancette** [comment]
@mateusz-lichota Thanks for getting this started.

This is quite a large PR, so it is hard to review and to get in (you can see that it already has some conflicts).  What I'm going to suggest here is that you split this up into a series of smaller PRs that will be much easier to review.

To split it up, I'll suggest the following course of action:
1.  Do an initial PR that just adds type annotations for the "obvious" and "easy" parts.  These are annotations that don't require importing new modules or defining new types.
2. For the remaining changes, split it up in a per-file (or at least per-functional area) basis.  For instance, put all of the changes to `client.py` and `service.py` in one PR, put the changes to `executor.py` in another, etc.

**Comment by mateusz-lichota** [comment]
Okay, I've created the first two smaller PRs with improved typings for Subscription (#995) and Publisher (#996). More PRs to follow.

**Comment by ihasdapie** [comment]
Thanks for the initiative!

I was just about to dig through rclpy to wrap https://github.com/ros2/rclpy/pull/974 up but seems like you've beat me to it :) What my PR currently does is I combed through all 154 matches of `= None` in the codebase and made Optional things, well, `Optional`. I'll rename my PR to scope it down to only the Optional fixes since it doesn't appear that you have went ahead and done that yet.

**Comment by ycheng517** [comment]
Any updates on this PR?

**Comment by clalancette** [comment]
> Any updates on this PR?

This PR needs to be rebased and split into smaller, more reviewable chunks.  If you are willing to spend some time doing that and opening new PRs, we are happy to review.

**Pull request closed without merging**
