### PR TITLE
Add types to time_source.py

### PR DESCRIPTION
**Pull request by InvincibleRMC**

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Looks reasonable to me.  I'm going to run CI on this one.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20616/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14969/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21340/)
* RHEL [Build Status](http://ci.ros2.org/job/ci_linux-rhel/623/)

**Comment by clalancette** [comment]
@InvincibleRMC There are some flake8 errors here, can you take a look?

**Review by fujitatomoya — APPROVED** [review]
lgtm with green CI

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20618/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14971/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21343/)

**Pull request merged**
