### PR TITLE
Changelog version to master

### PR DESCRIPTION
**Pull request by sloretz**
This brings the version and CHANGELOG on `master` up to date with the `dashing` branch.

@nuclearsandwich what's your opinion on keeping `master`'s version up to date with the latest release?

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
> This brings the version and CHANGELOG on `master` up to date with the `dashing` branch

As an aside while we're discussing changelog updates, have there been any updates to rclpy in Crystal that we should also consider pulling?



> @nuclearsandwich what's your opinion on keeping `master`'s version up to date with the latest release?

It is something I'd heartily endorse if we can find a straightforward way to manage them without manual labor and/or merge conflicts. How difficult was one this to perform?

One further concern is will this interfere with `catkin_generate_changelog` in a scenario like:

* commit is made to master
* commit is backported to dashing
* dashing gets a new changelog via `catkin_generate_changelog` and is tagged 0.7.x
* master gets a new changelog via `catkin_generate_changelog` and is tagged 0.8.0

I would expect that the commit shows up in the 0.8.0 changelog if the backport PR is squash merged but not if it is merged with a merge commit although it depends on what tags `catkin_generate_changelog` examines (those on the current branch or all).

---

Looking for precedence, using ROS 1 *-devel branches I  would expect we have divergent changelogs once a new -devel branch is created with point releases still occurring on the previous -devel branch. Do we do anything about changelogs in that case? Since we branch off of mainline unconditionally for each ROS 2 release the problem is more extreme than in ROS 1 where a repo may share one devel branch for all compatible forward development in which case there's no divergence in changelog.

**Comment by sloretz** [comment]
> It is something I'd heartily endorse if we can find a straightforward way to manage them without manual labor and/or merge conflicts. How difficult was one this to perform?

Pretty easy.

1. checkout branch from master
2. Cherry pick the commits that bump version and edit changelog `git cherry-pick -s abc123 def456`
3. Open PR

> One further concern is will this interfere with catkin_generate_changelog in a scenario like

Is step 5 is cherry pick changelog commits from `dashing` to `master`?

When master CHANGELOG.rst is generated in step 4, it looks like it gets all commits since the last release from master regardless of the tags on `dashing`. Step 5 see's merge conflicts when the cherry picks are performed. I think this is easy to resolve: take both and manually put releases in chronological order. Entries will be duplicated between `0.7.0` and `0.8.0`, but I think that's the right thing since those were the changes in that release.



> Looking for precedence, using ROS 1 *-devel branches I would expect we have divergent changelogs once a new -devel branch is created with point releases still occurring on the previous -devel branch. Do we do anything about changelogs in that case?

Not usually. `ros_comm` [`melodic-devel` CHANGELOG.rst](https://github.com/ros/ros_comm/blob/melodic-devel/ros_comm/CHANGELOG.rst) is missing `1.13.7` from [`lunar-devel` CHANGELOG.rst](https://github.com/ros/ros_comm/blob/lunar-devel/ros_comm/CHANGELOG.rst#1137-2018-08-17).

**Comment by nuclearsandwich** [comment]
To me this feels like more trouble than it is worth to adopt as a general practice but I don't have a problem with it. I was looking at index.ros.org and realized that this practice may have a negative consequence. The changelog field on https://index.ros.org/p/rclpy/#crystal appears to show changelog entries only for versions released in that rosdistro. I'm not sure what filtering technique is used there but merging changelog entries forward may interfere with it.

**Comment by sloretz** [comment]
> The changelog field on https://index.ros.org/p/rclpy/#crystal appears to show changelog entries only for versions released in that rosdistro. I'm not sure what filtering technique is used there but merging changelog entries forward may interfere with it.

@nuclearsandwich I didn't find any changelog filtering. It looks like `index.ros.org` [renders the whole changelog](https://github.com/ros-infrastructure/rosindex/blob/ros2/_plugins/rosindex_generator.rb#L342-L343) from [either the source entry or the tag of the last release](https://github.com/ros-infrastructure/rosindex/blob/7cc4b955c0b4bea080166fc1bcce3721b90a6688/_plugins/rosindex_generator.rb#L960-L968). I would expect those changelogs to be unchanged when merging changes to `master`.

**Pull request merged**
