### PR TITLE
reduce result_timeout to 10 sec from 15 mins.

### PR DESCRIPTION
**Pull request by fujitatomoya**
part of https://github.com/ros2/rcl/issues/1103

### CODE REVIEW

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2023-09-21/33733/2

**Review by fujitatomoya — COMMENTED** [review]
@clalancette this makes sense? along with https://github.com/ros2/rcl/pull/1012?

note, we should add this change after https://github.com/ros2/rcl/issues/1103 is fixed to avoid possible problem for `rclpy_action` server result availability.

**Review by iuhilnehc-ynos — APPROVED** [review]
LGTM.

It's better to define a new variable `result_timeout_default` to get the value of `rcl_action_server_get_default_options().result_timeout` from `rcl`, which is good for maintainance.

**Comment by fujitatomoya** [comment]
@clalancette @mjcarroll minor patch, could you take a look? (i think we can backport this to all distro?)

**Comment by fujitatomoya** [comment]
@clalancette as we talked today's call, requesting review on this.

**Comment by fujitatomoya** [comment]
@ahcorde @Barry-Xu-2018 @clalancette requesting review on this one, this actually aligns with `rclcpp_action`.

**Comment by Barry-Xu-2018** [comment]
LGTM

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21577/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15866/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1075/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22297/)

**Review by ahcorde — APPROVED** [review]

**Comment by fujitatomoya** [comment]
The previous CI build is failed, since there was a type.

```bash
04:06:41 CMake Error: Unknown argument --pakcages-up-to
```

CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21583/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15872/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1082/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22303/)

**Pull request merged**
