### PR TITLE
call ok() to see if rclpy and context is initialized.

### PR DESCRIPTION
**Pull request by fujitatomoya**
address https://github.com/ros2/rclpy/issues/190

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
@sloretz https://github.com/ros2/rclpy/issues/190 is way too old even before we introduce the `context` (dds participant entity instead of binding each node), as you mentioned we could just go ahead to close the issue. but i think test could be enhanced to call `ok()`.

**Review by EricCousineau-TRI — APPROVED** [review]
Looks great, thanks!

**Review by adityapande-1995 — APPROVED** [review]

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19769/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14271/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20495/)

**Comment by fujitatomoya** [comment]
@clalancette why did you abort https://ci.ros2.org/job/ci_linux-aarch64/14271/? by accident? just checking if i can restart the CI for that.

**Comment by clalancette** [comment]
> @clalancette why did you abort https://ci.ros2.org/job/ci_linux-aarch64/14271/?

It was hung.  It had been stuck on the same test for 4 hours, which is longer than full CI on aarch64 usually takes :).

**Comment by clalancette** [comment]
The unstable builds on aarch64 are happening right now, even without this PR.  So I'll go ahead and merge it.

**Pull request merged**
