### PR TITLE
Don't persist node and context between tests

### PR DESCRIPTION
**Pull request by rotu**
Maybe fix https://github.com/ros2/rmw_cyclonedds/issues/117
Signed-off-by: Dan Rose <dan@digilabs.io>

### CODE REVIEW

**Comment by rotu** [comment]
@emersonknapp could you please review this? I can't seem to reproduce the original error locally, but this seems the likely culprit.

**Comment by emersonknapp** [comment]
@ros2/aws-oncall  - please run this CI job
Gist: https://gist.githubusercontent.com/emersonknapp/df99345d71fabde7dc19d7cbb242c8ba/raw/c0dd6e8dcb15d2f5f54b48df4ec7e11df921450a/ros2.repos
BUILD args: --packages-up-to rclpy
TEST args: --packages-select rclpy
Job: ci_launcher

**Comment by emersonknapp** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9768/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5388/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7937/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9633/)

**Comment by rotu** [comment]
Oops. Fixed flake8 mistake

**Comment by emersonknapp** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9769/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5389/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7938/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9634/)

**Comment by rotu** [comment]
Unrelated test failures. :shipit:

**Comment by emersonknapp** [comment]
Verified that those failures are already present in the nightly windows build https://ci.ros2.org/view/nightly/job/nightly_win_deb/1568/#showFailuresLink. 

I don't have merge access though so this'll need approval from a maintainer

**Comment by clalancette** [comment]
This seems reasonable to me, but needs a rebase since it has a conflict now.

**Comment by rotu** [comment]
Thank for the heads-up, @clalancette.

It's rather dispiriting to have to "fix" a PR 9 days later through no fault of my own. How do I request a timely review and merge for a PR once development is complete?

**Comment by clalancette** [comment]
FYI: locally flake8 complained that the line that created the node was > 99 characters.  So I fixed that, but I'm honestly not sure why CI didn't pick it up earlier.  I'm going to run one more CI here just to be sure it is happy, then I'll merge.

**Comment by clalancette** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9932/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5542/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8080/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9781/)

**Comment by rotu** [comment]
Build failures do not appear caused by this PR. What is my next step to move this PR forward?

**Comment by clalancette** [comment]
All right, rebased to take care of the compiler issues.  One more CI :crossed_fingers: 

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9941/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5549/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8087/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9795/)

**Comment by rotu** [comment]
Yay! Green!

**Comment by clalancette** [comment]
The windows test failures are all flakes, and can be seen in earlier nightlies.  Thus, I'll go ahead and merge this.  Thanks for the contribution.

**Pull request merged**
