### PR TITLE
Handle take failure in `wait_for_message`

### PR DESCRIPTION
**Pull request by mhidalgo-bdai**
Closes https://github.com/ros2/rclpy/issues/1169. As mentioned there, this is much easier to fix than it is to reproduce and regress test.

### CODE REVIEW

**Comment by mhidalgo-bdai** [comment]
FYI @ksharma-bdai

**Review by clalancette — APPROVED** [review]
Yes, this is definitely the right thing to do.  I'll run CI on it next.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19567/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14080/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20291/)

**Review by fujitatomoya — APPROVED** [review]
lgtm

**Comment by mhidalgo-bdai** [comment]
@clalancette @fujitatomoya could this be backported to both Iron and Humble?

**Comment by clalancette** [comment]
> @clalancette @fujitatomoya could this be backported to both Iron and Humble?

Yeah, that seems reasonable.

**Comment by clalancette** [comment]
@Mergifyio backport humble iron

**Pull request merged**
