### PR TITLE
[Dashing] MultiThreadedExecutor spin_until_future complete should not continue waiting when the future is done.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
Backports #605

### CODE REVIEW

**Review by ivanpauno — APPROVED** [review]
Thanks for doing the backport!
LGTM with green CI

**Comment by nuclearsandwich** [comment]
@ros-pull-request-builder retest this please

**Comment by nuclearsandwich** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14663/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9416/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12327/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14807/)

**Comment by nuclearsandwich** [comment]
Hmm this change is causing the executor test to time out on the build farm and I just checked that this doesn't happen on a clean build of rclpy in Dashing [Build Status](https://build.ros2.org/job/Ddev__rclpy__ubuntu_bionic_amd64/)

**Comment by sloretz** [comment]
Since Dashing is EOL I'll assume it's ok to close this.

**Pull request closed without merging**
