### PR TITLE
Revert "Add types to Action Server and Action Client (#1349)"

### PR DESCRIPTION
**Pull request by fujitatomoya**
This reverts commit d1d7d0540ca9769e98dd11cf5d52622d9e0b2ace.

Depends on https://github.com/ros2/rclpy/pull/1360

### CODE REVIEW

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclpy#1359
Gist: https://gist.githubusercontent.com/fujitatomoya/dc3dbdca7e7553654c89d121b442b0e8/raw/89d37c0497ab232f028da4e80437b838a81c2b98/ros2.repos
BUILD args:  --packages-above-and-dependencies rclpy
TEST args:  --packages-above rclpy
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14576
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21853/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16123/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1359/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22564/)

**Comment by InvincibleRMC** [comment]
Just fyi #1345 built off changes done in #1349 So that is why you are receiving failures.

**Comment by fujitatomoya** [comment]
@InvincibleRMC so we should revert https://github.com/ros2/rclpy/pull/1345 together? what do you suggest?

**Comment by InvincibleRMC** [comment]
Until we can sort out the failure I think we have to unfortunately.

**Comment by InvincibleRMC** [comment]
I have some potential ideas for what could be causing problems with the rhel failures but don't have enough confidence for an exact cause without having access to a rhel system.

**Comment by fujitatomoya** [comment]
@InvincibleRMC thanks for taking care of this.

> I have some potential ideas for what could be causing problems with the rhel failures but don't have enough confidence for an exact cause without having access to a rhel system.

i think we can give it a shot, once you create the PR, i can start the CI with RHEL.

> Until we can sort out the failure I think we have to unfortunately.

So what we should do is the following, right? just checking.

1. revert https://github.com/ros2/rclpy/pull/1345
2. revert https://github.com/ros2/rclpy/pull/1349 (this PR)

**Comment by InvincibleRMC** [comment]
Yes that seems the best course of action to me

**Comment by fujitatomoya** [comment]
https://github.com/ros2/rclpy/pull/1360 has been merged, so i just did the rebase this PR against rolling. i will start the CI again.

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclpy#1359
Gist: https://gist.githubusercontent.com/fujitatomoya/cd35936b4f64d833241eef04925e2712/raw/89d37c0497ab232f028da4e80437b838a81c2b98/ros2.repos
BUILD args:  --packages-above-and-dependencies rclpy
TEST args:  --packages-above rclpy
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14579
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21856/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16126/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1362/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22567/)

**Comment by fujitatomoya** [comment]
windows failure is unrelated https://ci.ros2.org/job/ci_windows/22567/, i will go ahead to merge this revert PR.

**Pull request merged**
