### PR TITLE
[galactic] reject cancel request if failed to transit to CANCEL_GOAL state. (#791)

### PR DESCRIPTION
**Pull request by jacobperron**
Backport #791 to Galactic.

### CODE REVIEW

**Review by ivanpauno — APPROVED** [review]

**Review by cottsay — APPROVED** [review]

**Review by fujitatomoya — APPROVED** [review]

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14620/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9375/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12286/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14756/)

**Comment by fujitatomoya** [comment]
https://ci.ros2.org/job/ci_linux-aarch64/9375/testReport/junit/ros2param.ros2param.test/test_verb_list/test_verb_list/ is known issue, just flaky not related to this fix. i will retry CI again just in case.

**Comment by fujitatomoya** [comment]
CI(retry):
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14623/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9378/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12289/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14763/)

**Comment by jacobperron** [comment]
@fujitatomoya That's okay if it's a known flake; we don't need to rerun it. I'd like to see Windows go green(ish) once infrastructure cooperates.

**Comment by jacobperron** [comment]
Windows: [Build Status](https://ci.ros2.org/job/ci_windows/14776/)

**Pull request merged**
