### PR TITLE
Revert "Adds types to Lifecycle Objects"

### PR DESCRIPTION
**Pull request by fujitatomoya**
Reverts ros2/rclpy#1338

This re-generates the flaky for RHEL, see more details for https://github.com/ros2/ros2cli/issues/932.

closes https://github.com/ros2/ros2cli/issues/932

### CODE REVIEW

**Comment by fujitatomoya** [comment]
CI (Full):
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21992/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16255/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1504/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22727/)

**Review by clalancette — APPROVED** [review]
This looks good to me, assuming that Linux-rhel comes back green.

**Comment by fujitatomoya** [comment]
retry CI:
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1509/)
* Linux-rhel-debug [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1510/)

**Comment by fujitatomoya** [comment]
So reverting this does not turn the RHEL back on green.

i thought that this revert seems to address original flaky reported https://ci.ros2.org/job/nightly_linux-rhel_release/2047/testReport/projectroot/test/test_graph__rmw_fastrtps_cpp/ in https://github.com/ros2/ros2cli/issues/932#issuecomment-2411385246

but recently, this is not happening in RHEL nightly debug,

- https://ci.ros2.org/view/nightly/job/nightly_linux-rhel_debug/2075/ looks exactly same with https://github.com/ros2/rclpy/pull/1373#issuecomment-2414477371
- https://ci.ros2.org/view/nightly/job/nightly_linux-rhel_debug/2074/testReport/junit/launch_testing_examples.launch_testing_examples/check_node_launch_test/launch_testing_examples_check_node_launch_test/ looks another flaky test
- https://ci.ros2.org/view/nightly/job/nightly_linux-rhel_debug/2073/ looks exactly same with https://github.com/ros2/rclpy/pull/1373#issuecomment-2414477371
- https://ci.ros2.org/view/nightly/job/nightly_linux-rhel_debug/2072/testReport/junit/launch_testing_examples.launch_testing_examples/hello_world_launch_test/launch_testing_examples_hello_world_launch_test/ looks another flaky test
- https://ci.ros2.org/view/nightly/job/nightly_linux-rhel_debug/2071/ looks exactly same with https://github.com/ros2/rclpy/pull/1373#issuecomment-2414477371

according to last 3 days release/debug RHEL nightly result, i do not think reverting this is the right way...

**Comment by fujitatomoya** [comment]
Some experimental RHEL jobs are running, hopefully this can tell us which commit generates the error. (if that comes on green, that is the suspect.)

- https://github.com/fujitatomoya/ros2cli/tree/experimental/revert-933 (https://gist.githubusercontent.com/fujitatomoya/f495e432f68344f5b10b21979816cda2/raw/1a52201b1f3d23f85360667fa80b244260a77e77/ros2.repos)
  - RHEL Debug: [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1520/)
  - RHEL Release: [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1521/)
- https://github.com/fujitatomoya/rclpy/tree/experimental/revert-1220 (https://gist.githubusercontent.com/fujitatomoya/0ad0f0c7c5e5f1755e7b86ecd8fa7fcc/raw/c051a66bdb00dda02d7f13c124e99239d311aba6/ros2.repos)
  - RHEL Debug: [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1522/)
  - RHEL Release: [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1523/)
- https://github.com/fujitatomoya/rclpy/tree/experimental/revert-1363 (https://gist.githubusercontent.com/fujitatomoya/18ec1acb12d69a99ba1b9495afd6339a/raw/7ddad9c5f606da28bf23bb55ab4b6a6f41cd500e/ros2.repos)
  - RHEL Debug: [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1524/)
  - RHEL Release: [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1525/)
- https://github.com/fujitatomoya/rclpy/tree/experimental/revert-1369 (https://gist.githubusercontent.com/fujitatomoya/bdb3eeb9775510e161db8357e67e9eab/raw/eaf3ac31818979d5415ab43d79150e5036ef7a73/ros2.repos)
  - RHEL Debug: [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1526/)
  - RHEL Release: [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1527/)

**Comment by fujitatomoya** [comment]
i will go ahead to close this. because this is NOT the cause of the flake8 segmentation fault, and we can keep tracking with https://github.com/ament/ament_lint/pull/505.

**Pull request closed without merging**
