### PR TITLE
Issue 1064

### PR DESCRIPTION
**Pull request by sebastian-freitag**
This fixes https://github.com/ros2/rclpy/issues/1064. 
When building with Clang, tell cmake to link atomic
to the _rclpy_pybind11 target.

Signed-off-by: Sebastian Freitag
<sebastian.freitag@pylot.tech>

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]

**Comment by fujitatomoya** [comment]
either @adityapande-1995 or @sloretz , i do need second review on this, could you take a look at this?

**Review by adityapande-1995 — APPROVED** [review]
Looks good, I'll run full CI on this.

**Comment by adityapande-1995** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17964/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12503/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18608/)

**Comment by adityapande-1995** [comment]
CI round 2 : 
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17967/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12506/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18611/)

**Comment by sebastian-freitag** [comment]
I looked at the Linux build failures. They look very very unrelated to the change. Is the main on linux broken/unstable at the moment?

**Comment by mjcarroll** [comment]
@sebastian-freitag I believe a merge from rolling should be sufficient.  I tried to push to your branch to fix that, but have insufficient permissions.  Feel free to ping once you have done that and we can run CI again.

**Comment by mjcarroll** [comment]
I can confirm that this resolves issues with clang-14 for me.

**Comment by sebastian-freitag** [comment]
@mjcarroll done.

**Comment by mjcarroll** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17996/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12526/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18634/)

**Pull request merged**
