### PR TITLE
Merge Post galactic freeze into Rolling

### PR DESCRIPTION
**Pull request by sloretz**
Part of #665 - This includes all the pybind11 changes that we want to merge in Galactic patch 1. Before that, we've got to update rolling. All code here has already has been reviewed and approved.

I think rebase and merge would be good as that preserves the history of a bunch of different squash/merged PRs.

### CODE REVIEW

**Comment by sloretz** [comment]
DCO bot is unhappy, not sure why. All of these commits are squash/merges - maybe github doesn't signoff them? It seems reasonable to set the DCO bot to pass since individually these PRs all passed.

**Comment by clalancette** [comment]
> DCO bot is unhappy, not sure why. All of these commits are squash/merges - maybe github doesn't signoff them? It seems reasonable to set the DCO bot to pass since individually these PRs all passed.

Yeah, that seems reasonable to me.

On another note, I'll suggest we do a full build-n-test with these changes in place (including Windows Debug).  I know we've done that for the individual PRs, but this is a big enough change that a full CI is warranted.

**Comment by sloretz** [comment]
>  I'll suggest we do a full build-n-test with these changes in place (including Windows Debug)

Seems like a reasonable way to double check everything, especially Windows debug since this hasn't had the nightlies run on it.

CI (build: `--packages-above-and-dependencies rclpy` test: `--packages-above rclpy`)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14499/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9258/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12166/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14599/)
* Windows Debug [Build Status](https://ci.ros2.org/job/ci_windows/14600/)

**Review by ahcorde — APPROVED** [review]

**Comment by sloretz** [comment]
CI green :heavy_check_mark: and approved :tada: `Rebase and merge`ing!

**Pull request merged**
