### PR TITLE
QoS history depth is only available with KEEP_LAST.

### PR DESCRIPTION
**Pull request by fujitatomoya**
follow-up for https://github.com/ros2/rclpy/pull/849 (see comment https://github.com/ros2/rclpy/pull/849#discussion_r774688205)

Signed-off-by: Tomoya Fujita <Tomoya.Fujita@sony.com>

### CODE REVIEW

**Comment by fujitatomoya** [comment]
@ivanpauno requesting review on this.

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15858/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10535/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13523/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16153/)

**Comment by fujitatomoya** [comment]
CI(repo URL is fixed)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15873/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10550/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13539/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16175/)

**Review by ivanpauno — APPROVED** [review]
Thanks for the fix @fujitatomoya !!

**Pull request merged**
