### PR TITLE
Document qos_profile_* constants

### PR DESCRIPTION
**Pull request by jacobperron**
Forward port of #653 (from Foxy).

I plan to keep the two commits separate when merging.

### CODE REVIEW

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13336/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8266/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11068/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13387/)

**Review by sloretz — APPROVED** [review]
LGTM, though I think this repo has new PRs landing on master with backporting to older branches happening afterwards. It looks a little backwards in this case, though I don't think that will break anything.

**Comment by jacobperron** [comment]
> I think this repo has new PRs landing on master with backporting to older branches happening afterwards. It looks a little backwards in this case, though I don't think that will break anything.

Yeah, you're right. I was going to ask the contributor to re-target the original PR to master, but figured opening up a forward port was easy enough as the change is documentation only.

**Comment by jacobperron** [comment]
@ros-pull-request-builder retest this please

**Pull request merged**
