### PR TITLE
force using explicit kwargs

### PR DESCRIPTION
**Pull request by dirk-thomas**
* [Build Status](http://ci.ros2.org/job/ci_linux/2399/)

### CODE REVIEW

**Comment by dhood** [comment]
If I understand the implications of this correctly, won't it break demos e.g. https://github.com/ros2/demos/blob/master/demo_nodes_py/topics/listener_qos_py.py#L49 ?

**Comment by mikaelarguedas** [comment]
it will, demos and examples need to be updated accordingly

**Comment by dirk-thomas** [comment]
Here we go including the referenced PRs: [Build Status](http://ci.ros2.org/job/ci_linux/2401/)

**Comment by mikaelarguedas** [comment]
I know it's not tested by ci and a reflection of the demos, but can you update https://github.com/ros2/tutorials/ accordingly too ? thanks!

**Comment by dirk-thomas** [comment]
* https://github.com/ros2/ros2/wiki/Rosbag-with-ROS1-Bridge/_compare/ff21d181b126d2b4e8484dd4f45bdb9939684783...4a6dfb3ef6fe0447185da37c042ea86559663a21

**Pull request merged**
