### PR TITLE
Use py::class_ for rmw_qos_profile_t

### PR DESCRIPTION
**Pull request by hidmic**
Part of #665. Precisely what the title says. This data structure remains opaque, as it is redundant with those found in `qos.py`. I still feel the urge to rewrite `qos.py` in full, but I'll hold back.

### CODE REVIEW

**Comment by hidmic** [comment]
I'll rebase once https://github.com/ros2/rclpy/pull/739 goes in.

**Review by sloretz — APPROVED** [review]
LGTM with green CI and a rebase

**Comment by hidmic** [comment]
CI up to `rclpy`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14167/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8966/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11847/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14266/)

**Comment by hidmic** [comment]
@ros-pull-request-builder retest this please.

**Comment by hidmic** [comment]
CI up to `rclpy`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14170/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8969/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11851/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14270/)
* Windows Debug [Build Status](http://ci.ros2.org/job/ci_windows/14271/)

**Comment by hidmic** [comment]
@ros-pull-request-builder retest this please.

**Comment by hidmic** [comment]
Alright CI and reviewers are happy. Going in!

**Pull request merged**
