### PR TITLE
Use py::class_ for rcl_event_t

### PR DESCRIPTION
**Pull request by sloretz**
Part of #665 

This uses a `py::class_` definition for `rcl_event_t`

### CODE REVIEW

**Comment by sloretz** [comment]
Windows Debug CI (build: `--packages-up-to rclpy` test: `--packages-select rclpy`) [Build Status](https://ci.ros2.org/job/ci_windows/14291/)

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
build: `--packages-up-to rclpy` test: `--packages-select rclpy`

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14206/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9004/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11898/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14309/)

**Comment by sloretz** [comment]
Rebased without making any changes

CI (build: `--packages-above-and-dependencies rclpy` test: `--packages-above rclpy`)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14212/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9012/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11905/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14315/)

**Comment by sloretz** [comment]
Rebased without changes

CI (build: `--packages-up-to rclpy` test: `--packages-select rclpy`)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14220/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9020/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11911/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14321/)

**Comment by sloretz** [comment]
Approved and CI LGTM, merging!

**Pull request merged**
