### PR TITLE
[foxy] memory leak (#643)

### PR DESCRIPTION
**Pull request by fujitatomoya**
https://github.com/ros2/rclpy/issues/643 backport for foxy

Signed-off-by: Tomoya.Fujita <Tomoya.Fujita@sony.com>

Co-authored-by: Chen Lihui <lihui.chen@sony.com>

### CODE REVIEW

**Comment by fujitatomoya** [comment]
CC: @iuhilnehc-ynos

**Review by iuhilnehc-ynos — APPROVED** [review]

**Comment by fujitatomoya** [comment]
@clalancette 

this one is foxy backport of https://github.com/ros2/rclpy/pull/645, could you also check?

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13272/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8203/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10989/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13303/)

**Comment by clalancette** [comment]
The test warnings are all coming from elsewhere, so I'm going to go ahead and merge this.  Thanks for the backport.

**Pull request merged**
