### PR TITLE
[Foxy] fix memory leak for get_(publishers|subscriptions)_info_by_topic.

### PR DESCRIPTION
**Pull request by darkain84**
## Bug report

* Operating System: Ubuntu 20.04.2 LTS (5.8.0-41-generic)
* Version or commit hash: https://github.com/ros2/rclpy/commit/1bebfa252d1314ac636bf31d2a86dbe28f759e0c
* Client library (if applicable): rclpy (foxy)
* Python version: python 3.8

Steps to reproduce issue: 
> Run the below code on env which has lots of topics.

```python
import rclpy
from rclpy.node import Node

class MonitoTopics(Node):

    def __init__(self):
        super().__init__('monitor_topics')
        self._timer = self.create_timer(
            timer_period_sec=1.0, 
            callback=self._monitor_topics)

    def _monitor_topics(self):
        for topic_name, topic_types in self.get_topic_names_and_types():
            del topic_types
            for topic_info in self.get_publishers_info_by_topic(topic_name):
                del topic_info
            for topic_info in self.get_subscriptions_info_by_topic(topic_name):
                del topic_info


def main(args=None):
    rclpy.init(args=args)

    node = MonitoTopics()
    rclpy.spin(node)

    # Destroy the node explicitly
    # (optional - otherwise it will be done automatically
    # when the garbage collector destroys the node object)
    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
```

Expected behavior
> Memory usage is stable.

Actual behavior
> Memory usage keeps increasing.

Additional information

On python [c-api doc](https://docs.python.org/3.8/c-api/dict.html#c.PyDict_SetItemString), 
> int PyDict_SetItemString(PyObject *p, const char *key, PyObject *val)
> Insert val into the dictionary p using key as a key. key should be a const char*. The key object is created using 
> PyUnicode_FromString(key). Return 0 on success or -1 on failure. This function does not steal a reference to val.

The caller should handle reference of `val` obj when it succeeded. So we need to decrease reference 
at [this](https://github.com/ros2/rclpy/blob/foxy/rclpy/src/rclpy_common/src/common.c#L423).

### CODE REVIEW

**Comment by fujitatomoya** [comment]
This problem only happens on foxy.

**Review by fujitatomoya — APPROVED** [review]
lgtm

**Comment by fujitatomoya** [comment]
@sloretz could you take a look? i think this is bug.

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16925/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11491/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17324/)

**Comment by sloretz** [comment]
Foxy failures are probably an existing issue, but they'll need investigation to be sure: https://github.com/ros2/rosidl/pull/639#issuecomment-1182585035

**Comment by sloretz** [comment]
CMake warnings are unrelated to this PR. CI LGTM :tada: 

Thanks for the PR!

**Pull request merged**
