### PR TITLE
Fix conflict and use new testcase

### PR DESCRIPTION
**Pull request by Barry-Xu-2018**
Move test added by https://github.com/ros2/rclpy/pull/1045 to this PR.

Fix backport #1042

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
@Barry-Xu-2018 why this does not have test_parameter_service.py?

**Comment by Barry-Xu-2018** [comment]
> why this does not have test_parameter_service.py?

Sorry. I miss to add this file.   
I fixed it.

**Review by fujitatomoya — APPROVED** [review]

**Comment by fujitatomoya** [comment]
@Barry-Xu-2018 @iuhilnehc-ynos can we start CI?

**Comment by iuhilnehc-ynos** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17777/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12323/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18422/)

**Comment by Barry-Xu-2018** [comment]
For window's failure, the all errors are the same.  Not sure if CI environment has certain problem.   
e.g.    
```
[ERROR] [test_publisher-29]: process has died [pid 22408, exit code 1, cmd 'C:/ci/ws/build/test_communication/Release/test_publisher_cpp.exe Strings /test_time_03_40_20']
```

**Review by iuhilnehc-ynos — APPROVED** [review]

**Comment by Barry-Xu-2018** [comment]
Now Galactic is EOL. So this fix should be closed.

**Pull request closed without merging**
