### PR TITLE
Implement signal handling in Python

### PR DESCRIPTION
**Pull request by sloretz**
Part of #665 because it removes the signal handler CPython extension

This implements signal handling in Python using the `signal` library rather than doing it in C. I think the benefits outweigh the drawbacks.

Benefits:
* Less C code to maintain
* Don't have to port the atomics usage in the sigint module to C++
* One less compilation unit depending on `rclpy_handle_...`
* Don't need to worry about signal safety in Python signal handler

Drawbacks
* The signal handler isn't run *exactly* when the signal happens - The real signal handler is setting a flag that tells CPython to call the Python signal handlers ASAP
* If pure C code takes a really really long time, the Python signal handler won't get called until the interpreter gets to run again
  * But C code taking a long time without releasing the GIL would already be a problem on its own
* It adds an extra frame to the stack-trace

With signal handling in C

```console
$ ros2 run examples_rclpy_minimal_publisher publisher_member_function
[INFO] [1616203329.647568651] [minimal_publisher]: Publishing: "Hello World: 0"
[INFO] [1616203330.133528959] [minimal_publisher]: Publishing: "Hello World: 1"
[INFO] [1616203330.633883396] [minimal_publisher]: Publishing: "Hello World: 2"
^CTraceback (most recent call last):
  File "/home/osrf/ws/ros2/install/examples_rclpy_minimal_publisher/lib/examples_rclpy_minimal_publisher/publisher_member_function", li
ne 11, in <module>
    load_entry_point('examples-rclpy-minimal-publisher', 'console_scripts', 'publisher_member_function')()
  File "/home/osrf/ws/ros2/build/examples_rclpy_minimal_publisher/examples_rclpy_minimal_publisher/publisher_member_function.py", line
43, in main
    rclpy.spin(minimal_publisher)
  File "/home/osrf/ws/ros2/install/rclpy/lib/python3.8/site-packages/rclpy/__init__.py", line 196, in spin
    executor.spin_once()
  File "/home/osrf/ws/ros2/install/rclpy/lib/python3.8/site-packages/rclpy/executors.py", line 693, in spin_once
    handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
  File "/home/osrf/ws/ros2/install/rclpy/lib/python3.8/site-packages/rclpy/executors.py", line 679, in wait_for_ready_callbacks
    return next(self._cb_iter)
  File "/home/osrf/ws/ros2/install/rclpy/lib/python3.8/site-packages/rclpy/executors.py", line 576, in _wait_for_ready_callbacks
    _rclpy.rclpy_wait(wait_set, timeout_nsec)
KeyboardInterrupt
```

With signal handling in Python, the last frame in the stack trace printed is a frame inside the Python signal handler.

```console
 ros2 run examples_rclpy_minimal_publisher publisher_member_function
[INFO] [1616203196.522705663] [minimal_publisher]: Publishing: "Hello World: 0"
[INFO] [1616203197.007797048] [minimal_publisher]: Publishing: "Hello World: 1"
[INFO] [1616203197.507855562] [minimal_publisher]: Publishing: "Hello World: 2"
^CTraceback (most recent call last):
  File "/home/osrf/ws/ros2/install/examples_rclpy_minimal_publisher/lib/examples_rclpy_minimal_publisher/publisher_member_function", li
ne 11, in <module>
    load_entry_point('examples-rclpy-minimal-publisher', 'console_scripts', 'publisher_member_function')()
  File "/home/osrf/ws/ros2/build/examples_rclpy_minimal_publisher/examples_rclpy_minimal_publisher/publisher_member_function.py", line
43, in main
    rclpy.spin(minimal_publisher)
  File "/home/osrf/ws/ros2/install/rclpy/lib/python3.8/site-packages/rclpy/__init__.py", line 196, in spin
    executor.spin_once()
  File "/home/osrf/ws/ros2/install/rclpy/lib/python3.8/site-packages/rclpy/executors.py", line 693, in spin_once
    handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
  File "/home/osrf/ws/ros2/install/rclpy/lib/python3.8/site-packages/rclpy/executors.py", line 679, in wait_for_ready_callbacks
    return next(self._cb_iter)
  File "/home/osrf/ws/ros2/install/rclpy/lib/python3.8/site-packages/rclpy/executors.py", line 576, in _wait_for_ready_callbacks
    _rclpy.rclpy_wait(wait_set, timeout_nsec)
  File "/home/osrf/ws/ros2/install/rclpy/lib/python3.8/site-packages/rclpy/signals.py", line 62, in __sigint_handler
    cls.__old_handler(signum, frame)
KeyboardInterrupt
```

### CODE REVIEW

**Comment by sloretz** [comment]
CI (build: `--packages-up-to rclpy` test: `--packages-select rclpy`)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14001/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8823/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11694/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14081/)

**Review by clalancette — COMMENTED** [review]
I have to say that I'm nervous about this in general.  I don't have anything specific to point to, but every time we've messed with the signal handling it takes quite a while to iron all of the bugs out.

That's not to say that we shouldn't do this; but I do think we should consider waiting on this one until after Galactic, which will give us a whole year to figure out where the bugs are.

**Review by hidmic — COMMENTED** [review]
This seems like a fine port, except for the fact this no longer chains signal handlers at the C level (CPython signal handling [doesn't do that](https://github.com/python/cpython/blob/ba251c2ae6654bfc8abd9d886b219698ad34ac3c/Modules/signalmodule.c#L516)). If Python signal handlers are setup before any C extension with proper chaining does so, we should be OK I guess.

**Comment by sloretz** [comment]
> I don't have anything specific to point to, but every time we've messed with the signal handling it takes quite a while to iron all of the bugs out.

Yeah, that's fair. I can leave this PR up until then. If we do that, I'll need to think of a way to be backwards compatible with the use of rclpy_handle for guard conditions in the C code as we eliminate rclpy_handle_t elsewhere.

**Comment by sloretz** [comment]
Re-re-targeted back to master and re-marking as draft. This should stay in rolling for a while before it's considered for backport (if at all).

**Comment by ahcorde** [comment]
@sloretz is there any way to retarget this to `post_galactic_freeze`  ? I converted GuardCondition to use C++ classes, but I had to cherry-pick these two commits.

**Comment by sloretz** [comment]
This PR is ready for review to be merged into `master`/Rolling. It should **not** be backported.

CI (build: `--packages-up-to rclpy` test: `--packages-select rclpy`)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14505/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9262/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12170/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14604/)

**Comment by sloretz** [comment]
@ros-pull-request-builder retest this please

**Review by ahcorde — APPROVED** [review]

**Comment by clalancette** [comment]
Can I suggest we do a full build+test before we merge this one?  That will at least give us an idea if any of the signals that launch files send to processes have problems.

**Comment by sloretz** [comment]
All downstream packages CI (build: `--packages-above-and-dependencies rclpy` test: `--packages-above rclpy`)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14567/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9323/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12230/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14691/)

**Comment by sloretz** [comment]
I'm going to close this in favor of #814. Using Python's built-in signal library has a lot of downsides, and being only able to register and unregister a signal handler from the same thread Python was initialized in is especially hard to work around.

**Pull request closed without merging**
