### PR TITLE
[Foxy] fix memory leak for serialization

### PR DESCRIPTION
**Pull request by iuhilnehc-ynos**
to fix https://github.com/ros2/rclpy/issues/897

Signed-off-by: Chen Lihui <lihui.chen@sony.com>

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
This seems reasonable to me, and fixes the problem in my testing.  @sloretz can you take a look?

**Review by fujitatomoya — APPROVED** [review]

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16189/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10816/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16540/)

**Comment by fujitatomoya** [comment]
@clalancette window fails right away, https://ci.ros2.org/job/ci_windows/16540/console i am not even sure what is going on here. do you know anything?

**Comment by clalancette** [comment]
> @clalancette window fails right away, https://ci.ros2.org/job/ci_windows/16540/console i am not even sure what is going on here. do you know anything?

I think one of our Windows workers is having trouble.  I got the job to start running on a different worker; it's going now.

**Comment by fujitatomoya** [comment]
CI: (retry)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16249/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10870/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16606/)

**Comment by fujitatomoya** [comment]
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16677/)

**Comment by fujitatomoya** [comment]
@iuhilnehc-ynos @clalancette 

windows unstable, i do not think there errors are related to this fix. any thoughts?

**Comment by iuhilnehc-ynos** [comment]
Yes, it's unrelated to `rclpy`. The deprecated warning is from `pytest-7.0.1`.

https://github.com/pytest-dev/pytest/discussions/9616#discussioncomment-2117546 might need to be added in the ci builder for windows.

**Pull request merged**
