### PR TITLE
Add history and depth to topic endpoint string

### PR DESCRIPTION
**Pull request by jacobperron**
I'm not sure why history and depth were left out originally. Maybe @jaisontj or @mm318 can answer?

AFAICT, we seem to be able to get this info from the endpoints just fine.

### CODE REVIEW

**Comment by mm318** [comment]
I think it was left out because the history and depth QoS settings didn't contribute to QoS incompatibility, and this feature was implemented with debugging QoS incompatibilities in mind.

Overall, it was an oversight. Thanks for making the enhancement!

**Review by mm318 — APPROVED** [review]

**Review by fujitatomoya — APPROVED** [review]
lgtm

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13759/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8626/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11469/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13834/)

**Comment by jacobperron** [comment]
So, I guess I got lucky with the default rmw. It looks like the history and depth values are only reported by rmw_cyclonedds_cpp, and not rmw_fastrtps_cpp or rmw_connext_cpp. Instead, we always get

```
History: UNKNOWN
Depth: 0
```

Knowing that this data isn't provided by 2/3 of the officially supported RMWs, I'm not sure if it makes sense to move forward with this PR. What do others think?

cc/ @ivanpauno

**Comment by ivanpauno** [comment]
> Knowing that this data isn't provided by 2/3 of the officially supported RMWs, I'm not sure if it makes sense to move forward with this PR. What do others think?

I would say no, except that it can also be corrected in the other rmw implementations.
AFAIR not all qos settings are shared through discovery in DDS, only the ones that are used for qos matching.

I'm not sure what cyclonedds is doing, I will double check.

**Comment by emersonknapp** [comment]
> Knowing that this data isn't provided by 2/3 of the officially supported RMWs, I'm not sure if it makes sense to move forward with this PR. What do others think?

Ah yes, I remember this now. I think there is no requirement for the participants to report these values because they're "participant-internal" values. It's worth leaving a comment in this code to inform the next person to wonder about it.

**Comment by ivanpauno** [comment]
> I'm not sure what cyclonedds is doing, I will double check.

I tried, when you use a cyclonedds node and then call `ros2 topic info -v <topic_name>` also using cyclone it works correctly.
But if you create a node with fastrtps and then `ros2 topic info -v <topic_name>` with cyclonedds the information is not accurate.

i.e.: cyclone is sharing more metadata than what DDS requires (or that's my guess)

**Comment by jacobperron** [comment]
Closing, since history and depth info isn't available for most RMWs.

**Pull request closed without merging**
