### PR TITLE
[foxy] Destroy event handlers owned by publishers/subscriptions when calling publisher.destroy()/subscription.destroy() (#603)

### PR DESCRIPTION
**Pull request by jacobperron**
Backport #603 to Foxy.

### CODE REVIEW

**Review by ivanpauno — APPROVED** [review]
Thanks for doing the backport!!

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12915/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7869/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10632/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12864/)

**Comment by sloretz** [comment]
Re-running CI with typo in test args fixed (build: `--packages-above-and-dependencies rclpy` test: `--packages-above-and-dependencies rclpy`)

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12974/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7925/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10695/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12941/)

**Comment by jacobperron** [comment]
Test failures appear to be known failures.

**Pull request merged**
