### PR TITLE
fix sigint guard condition's lifecycle bug

### PR DESCRIPTION
**Pull request by reed-lau**
* fix https://github.com/ros2/rclpy/issues/215, https://github.com/ros2/rclpy/issues/253

Signed-off-by: reed-lau <geoliuwei@gmail.com>

### CODE REVIEW

**Comment by reed-lau** [comment]
int the executor.py  'sigint_gc' is related with `rclpy_get_sigint_guard_condition, rclpy_wait_set_add_entity, rclpy_destroy_entity` these three functions. the `rclpy_get_sigint_guard_condition` assign the sigint_gc to the global static variable `g_sigint_gc_handle`, but the  `rclpy_destroy_entity` function does not remove it. so sometimes, when we destroy it, and then Ctrl-C is triggered, the catch_function(signal handler function) will using the valid pointer.

**Comment by sloretz** [comment]
CI

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/6454/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2824/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5299/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/6273/)

**Comment by reed-lau** [comment]
change the code to the offical style, re-ci please

**Comment by sloretz** [comment]
CI
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/6459/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2829/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5304/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/6278/)

**Comment by sloretz** [comment]
CI ( I messed up the test parameters last time)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/6464/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2834/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5309/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/6283/)

**Comment by sloretz** [comment]
Thanks for the fix @reed-lau !

**Comment by reed-lau** [comment]
will this patch backport to bouncy-branch? as we're still using bouncy, compiling for source.

**Comment by sloretz** [comment]
@reed-lau I've added this PR to the list: ros2/ros2#575, though I don't know whether or not another bouncy patch release will happen.

**Pull request merged**
