### PR TITLE
Use CFFI to generate _rclpy_logging

### PR DESCRIPTION
**Pull request by sloretz**
This is a prototype using the `python-cffi` to generate the CPython extension instead of writing it ourselves. This pull request replaces _rclpy_logging with it. This is an alternative to pybind11 and #652.

CFFI works by giving it a definition file and a bit of extra C code with all the includes for those definitions, and asking it to generate a CPython extension. That extension is then compiled by CMake, and used in the Python code. In the case of _rclpy_logging it gets rid of all the manual CPython extension writing, and in the process moving all the logic that was in C into Python instead.

@cottsay @iantheengineer @azeey FYI

### CODE REVIEW

**Comment by sloretz** [comment]
Code size comparison - very minimal increase, likely because this approach exposes more C functions and types to Python.

`CMAKE_BUILD_TYPE=Debug` `master` branch

```console
-rw-r--r-- 1 sloretz sloretz 45K Jan  7 17:47 install/rclpy/lib/python3.8/site-packages/rclpy/_rclpy_logging.cpython-38-x86_64-linux-gnu.so
```

`CMAKE_BUILD_TYPE=Debug` this PR's branch
```console
-rw-r--r-- 1 sloretz sloretz 53K Jan  7 17:37 install/rclpy/lib/python3.8/site-packages/rclpy/_rclpy_logging.cpython-38-x86_64-linux-gnu.so
```

**Comment by sloretz** [comment]
CI (build: `--packages-above-and-dependencies rclpy` test: `--packages-above rclpy` CI branch: `add_python3_cffi`)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13378/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8301/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11104/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13429/)

**Comment by sloretz** [comment]
CI again with two new commits + rebased ros2/ci#531 for flak8 workaround

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13386/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8307/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11110/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13436/)

**Comment by sloretz** [comment]
Windows again with debug code: [Build Status](https://ci.ros2.org/job/ci_windows/13437/)

**Comment by ivanpauno** [comment]
Related to the comment [here](https://github.com/ros2/rclpy/pull/652#issuecomment-758875512), I think that if we use cffi for all our bindings ensuring that objects are destroyed in the correct order will be quite complicated.

**Comment by sloretz** [comment]
> Related to the comment here, I think that if we use cffi for all our bindings ensuring that objects are destroyed in the correct order will be quite complicated.

Yeah, making sure publishers are destroyed before nodes etc is more complicated than what can be done with Pybind11. CFFI offers essentially the same capability as pycapsule destructors, so it would be about the same complexity as it is now.

Upstream thoughts on destruction order
https://foss.heptapod.net/pypy/cffi/-/issues/340

**Comment by sloretz** [comment]
Closing; future work in #665

**Pull request closed without merging**
