### PR TITLE
Add `None` return to functions in the tests folder which do not return

### PR DESCRIPTION
**Pull request by InvincibleRMC**
This adds `None` type annotation to functions which take no inputs and return nothing. I understand this is a big PR and if it is too big I will split it up into smaller ones.

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]
lgtm with green CI

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclpy#1358
Gist: https://gist.githubusercontent.com/fujitatomoya/df5ddd92de46f7fbd7b4c45780230ecb/raw/d4a225117a62b661fa7b461ee574df76d2ccb99a/ros2.repos
BUILD args:  --packages-above-and-dependencies rclpy
TEST args:  --packages-above rclpy
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14629
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21910/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16178/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1421/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22631/)

**Comment by InvincibleRMC** [comment]
Hmm `ros2cli` is failing like #1349. I'm not really sure how that is possible since this code only changes unit tests in rclpy.

**Comment by fujitatomoya** [comment]
I heard that we found RHEL is unstable recently again, lets wait for windows then. lets keep this open until RHEL instability is fixed, i will get this back once that goes away to restart CI.

**Comment by InvincibleRMC** [comment]
> I heard that we found RHEL is unstable recently again, lets wait for windows then. lets keep this open until RHEL instability is fixed, i will get this back once that goes away to restart CI.

Ok please let me know when it gets fixed.

**Comment by clalancette** [comment]
All known issues have now been fixed, so I'll run CI again.

**Comment by clalancette** [comment]
Pulls: https://github.com/ros2/rclpy/pull/1358
Gist: https://gist.githubusercontent.com/clalancette/da6b7c58a4ac36fe3f2d3d70e23071f9/raw/d4a225117a62b661fa7b461ee574df76d2ccb99a/ros2.repos
BUILD args:  --packages-above-and-dependencies rclpy
TEST args:  --packages-above rclpy
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14644
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21927/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16194/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1441/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22653/)

**Comment by clalancette** [comment]
So it does indeed look like RHEL is having issues with this PR.  The [nightly job](https://ci.ros2.org/view/nightly/job/nightly_linux-rhel_release/2036/) didn't have any failures, while the CI job here did.  So this needs to be looked into before we can merge this.

**Comment by InvincibleRMC** [comment]
This is quite strange. How modifying test cases in rclpy causes only rhel ros2cli to fail.

**Comment by clalancette** [comment]
> This is quite strange. How modifying test cases in rclpy causes only rhel ros2cli to fail.

Agreed, I don't quite understand it myself, but there is a crash here in `pyflakes` that doesn't seem to be in the nightlies:

```
Current thread 0x00007f1724fe2740 (most recent call first):
  File "/usr/lib/python3.9/site-packages/pyflakes/checker.py", line 353 in __init__
  File "/usr/lib/python3.9/site-packages/pyflakes/checker.py", line 915 in __init__
  File "/usr/lib/python3.9/site-packages/flake8/plugins/pyflakes.py", line 94 in __init__
  File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 417 in run_check
  File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 493 in run_ast_checks
  File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 597 in run_checks
  File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 687 in _run_checks
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 48 in mapstar
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 125 in worker
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 108 in run
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 315 in _bootstrap
  File "/usr/lib64/python3.9/multiprocessing/popen_fork.py", line 71 in _launch
  File "/usr/lib64/python3.9/multiprocessing/popen_fork.py", line 19 in __init__
  File "/usr/lib64/python3.9/multiprocessing/context.py", line 277 in _Popen
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 121 in start
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 326 in _repopulate_pool_static
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 303 in _repopulate_pool
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 212 in __init__
  File "/usr/lib64/python3.9/multiprocessing/context.py", line 119 in Pool
  File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 664 in _try_initialize_processpool
  File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 260 in run_parallel
  File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 309 in run
  File "/usr/lib/python3.9/site-packages/flake8/main/application.py", line 271 in run_checks
  File "/usr/lib/python3.9/site-packages/flake8/api/legacy.py", line 109 in check_files
  File "/home/jenkins-agent/workspace/ci_linux-rhel/ws/install/ament_flake8/lib/python3.9/site-packages/ament_flake8/main.py", line 281 in generate_flake8_report
  File "/home/jenkins-agent/workspace/ci_linux-rhel/ws/install/ament_flake8/lib/python3.9/site-packages/ament_flake8/main.py", line 88 in main_with_errors
  File "/home/jenkins-agent/workspace/ci_linux-rhel/ws/src/ros2/ros2cli/ros2cli/test/test_flake8.py", line 22 in test_flake8
  File "/usr/lib/python3.9/site-packages/_pytest/python.py", line 183 in pytest_pyfunc_call
  File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3.9/site-packages/_pytest/python.py", line 1641 in runtest
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 162 in pytest_runtest_call
  File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 255 in <lambda>
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 311 in from_call
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 254 in call_runtest_hook
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 215 in call_and_report
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 126 in runtestprotocol
  File "/builddir/build/BUILDROOT/python-pytest-rerunfailures-9.1.1-3.el9.noarch/usr/lib/python3.9/site-packages/pytest_rerunfailures.py", line 240 in pytest_runtest_protocol
  File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3.9/site-packages/_pytest/main.py", line 348 in pytest_runtestloop
  File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3.9/site-packages/_pytest/main.py", line 323 in _main
  File "/usr/lib/python3.9/site-packages/_pytest/main.py", line 269 in wrap_session
  File "/usr/lib/python3.9/site-packages/_pytest/main.py", line 316 in pytest_cmdline_main
  File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 162 in main
  File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 185 in console_main
  File "/usr/lib/python3.9/site-packages/pytest/__main__.py", line 5 in <module>
  File "/usr/lib64/python3.9/runpy.py", line 87 in _run_code
  File "/usr/lib64/python3.9/runpy.py", line 197 in _run_module_as_main
```

**Comment by InvincibleRMC** [comment]
Since this is the same error as https://github.com/ros2/ros2cli/issues/932 Should I try making a PR not on rclpy? To See if its typing in general or if typing on rclpy specifically is the problem?

**Comment by fujitatomoya** [comment]
> How modifying test cases in rclpy causes only rhel ros2cli to fail.

I just cannot tell... This is really weird...

the difference between CI and nightly jobs are,

- `CI_CMAKE_BUILD_TYPE`: CI is `None`, nightly is `Release`.
- only nightly has `-DPython3_EXECUTABLE=/usr/bin/python3`. that i tested CI job, this does not help it.

<details><summary>Segmentation Fault Stack Trace</summary>

```bash
15:03:44 ============================= test session starts ==============================
15:03:44 platform linux -- Python 3.9.18, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
15:03:44 cachedir: /home/jenkins-agent/workspace/ci_linux-rhel/ws/build/ros2cli/.pytest_cache
15:03:44 rootdir: /home/jenkins-agent/workspace/ci_linux-rhel/ws/src/ros2/ros2cli, configfile: pytest.ini
15:03:44 plugins: launch-testing-3.6.1, ament-xmllint-0.18.1, ament-copyright-0.18.1, ament-pep257-0.18.1, ament-mypy-0.18.1, ament-flake8-0.18.1, ament-lint-0.18.1, timeout-1.4.2, mock-3.6.1, repeat-0.9.3, cov-4.0.0, colcon-core-0.17.0, rerunfailures-9.1.1
15:03:44 timeout: 900.0s
15:03:44 timeout method: thread
15:03:44 timeout func_only: False
15:03:44 collecting ... 
15:03:44 collected 31 items                                                             
15:03:44 
15:03:44 test/test_copyright.py .                                                 [  3%]
15:03:44 test/test_daemon.py ...................                                  [ 64%]
15:03:44 test/test_direct.py ....                                                 [ 77%]
15:03:44 Fatal Python error: Segmentation fault
15:03:44 
15:03:44 Current thread 0x00007fe9d0f72740 (most recent call first):
15:03:44   File "/usr/lib/python3.9/site-packages/pyflakes/checker.py", line 353 in __init__
15:03:44   File "/usr/lib/python3.9/site-packages/pyflakes/checker.py", line 915 in __init__
15:03:44   File "/usr/lib/python3.9/site-packages/flake8/plugins/pyflakes.py", line 94 in __init__
15:03:44   File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 417 in run_check
15:03:44   File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 493 in run_ast_checks
15:03:44   File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 597 in run_checks
15:03:44   File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 687 in _run_checks
15:03:44   File "/usr/lib64/python3.9/multiprocessing/pool.py", line 48 in mapstar
15:03:44   File "/usr/lib64/python3.9/multiprocessing/pool.py", line 125 in worker
15:03:44   File "/usr/lib64/python3.9/multiprocessing/process.py", line 108 in run
15:03:44   File "/usr/lib64/python3.9/multiprocessing/process.py", line 315 in _bootstrap
15:03:44   File "/usr/lib64/python3.9/multiprocessing/popen_fork.py", line 71 in _launch
15:03:44   File "/usr/lib64/python3.9/multiprocessing/popen_fork.py", line 19 in __init__
15:03:44   File "/usr/lib64/python3.9/multiprocessing/context.py", line 277 in _Popen
15:03:44   File "/usr/lib64/python3.9/multiprocessing/process.py", line 121 in start
15:03:44   File "/usr/lib64/python3.9/multiprocessing/pool.py", line 326 in _repopulate_pool_static
15:03:44   File "/usr/lib64/python3.9/multiprocessing/pool.py", line 303 in _repopulate_pool
15:03:44   File "/usr/lib64/python3.9/multiprocessing/pool.py", line 212 in __init__
15:03:44   File "/usr/lib64/python3.9/multiprocessing/context.py", line 119 in Pool
15:03:44   File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 664 in _try_initialize_processpool
15:03:44   File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 260 in run_parallel
15:03:44   File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 309 in run
15:03:44   File "/usr/lib/python3.9/site-packages/flake8/main/application.py", line 271 in run_checks
15:03:44   File "/usr/lib/python3.9/site-packages/flake8/api/legacy.py", line 109 in check_files
15:03:44   File "/home/jenkins-agent/workspace/ci_linux-rhel/ws/install/ament_flake8/lib/python3.9/site-packages/ament_flake8/main.py", line 281 in generate_flake8_report
15:03:44   File "/home/jenkins-agent/workspace/ci_linux-rhel/ws/install/ament_flake8/lib/python3.9/site-packages/ament_flake8/main.py", line 88 in main_with_errors
15:03:44   File "/home/jenkins-agent/workspace/ci_linux-rhel/ws/src/ros2/ros2cli/ros2cli/test/test_flake8.py", line 22 in test_flake8
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/python.py", line 183 in pytest_pyfunc_call
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/python.py", line 1641 in runtest
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 162 in pytest_runtest_call
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 255 in <lambda>
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 311 in from_call
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 254 in call_runtest_hook
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 215 in call_and_report
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 126 in runtestprotocol
15:03:44   File "/builddir/build/BUILDROOT/python-pytest-rerunfailures-9.1.1-3.el9.noarch/usr/lib/python3.9/site-packages/pytest_rerunfailures.py", line 240 in pytest_runtest_protocol
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/main.py", line 348 in pytest_runtestloop
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/main.py", line 323 in _main
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/main.py", line 269 in wrap_session
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/main.py", line 316 in pytest_cmdline_main
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 162 in main
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 185 in console_main
15:03:44   File "/usr/lib/python3.9/site-packages/pytest/__main__.py", line 5 in <module>
15:03:44   File "/usr/lib64/python3.9/runpy.py", line 87 in _run_code
15:03:44   File "/usr/lib64/python3.9/runpy.py", line 197 in _run_module_as_main
15:03:44 
15:03:44 +++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++
15:03:44 
15:03:44 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Captured stderr ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
15:03:44 option --max-complexity: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
15:03:44 option --application-import-names: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
15:03:44 option --application-package-names: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
15:03:44 option --import-order-style: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
15:03:44 option --quotes: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
15:03:44 option --inline-quotes: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
15:03:44 option --multiline-quotes: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
15:03:44 option --docstring-quotes: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
15:03:44 
15:03:44 ~~~~~~~~~~~~~~~~~~~~~ Stack of Thread-28 (140640541189696) ~~~~~~~~~~~~~~~~~~~~~
15:03:44   File "/usr/lib64/python3.9/threading.py", line 937, in _bootstrap
15:03:44     self._bootstrap_inner()
15:03:44   File "/usr/lib64/python3.9/threading.py", line 980, in _bootstrap_inner
15:03:44     self.run()
15:03:44   File "/usr/lib64/python3.9/threading.py", line 917, in run
15:03:44     self._target(*self._args, **self._kwargs)
15:03:44   File "/usr/lib64/python3.9/multiprocessing/pool.py", line 576, in _handle_results
15:03:44     task = get()
15:03:44   File "/usr/lib64/python3.9/multiprocessing/connection.py", line 254, in recv
15:03:44     buf = self._recv_bytes()
15:03:44   File "/usr/lib64/python3.9/multiprocessing/connection.py", line 418, in _recv_bytes
15:03:44     buf = self._recv(4)
15:03:44   File "/usr/lib64/python3.9/multiprocessing/connection.py", line 383, in _recv
15:03:44     chunk = read(handle, remaining)
15:03:44 
15:03:44 ~~~~~~~~~~~~~~~~~~~~~ Stack of Thread-27 (140640557975104) ~~~~~~~~~~~~~~~~~~~~~
15:03:44   File "/usr/lib64/python3.9/threading.py", line 937, in _bootstrap
15:03:44     self._bootstrap_inner()
15:03:44   File "/usr/lib64/python3.9/threading.py", line 980, in _bootstrap_inner
15:03:44     self.run()
15:03:44   File "/usr/lib64/python3.9/threading.py", line 917, in run
15:03:44     self._target(*self._args, **self._kwargs)
15:03:44   File "/usr/lib64/python3.9/multiprocessing/pool.py", line 528, in _handle_tasks
15:03:44     for taskseq, set_length in iter(taskqueue.get, None):
15:03:44 
15:03:44 ~~~~~~~~~~~~~~~~~~~~~ Stack of Thread-26 (140641354683968) ~~~~~~~~~~~~~~~~~~~~~
15:03:44   File "/usr/lib64/python3.9/threading.py", line 937, in _bootstrap
15:03:44     self._bootstrap_inner()
15:03:44   File "/usr/lib64/python3.9/threading.py", line 980, in _bootstrap_inner
15:03:44     self.run()
15:03:44   File "/usr/lib64/python3.9/threading.py", line 917, in run
15:03:44     self._target(*self._args, **self._kwargs)
15:03:44   File "/usr/lib64/python3.9/multiprocessing/pool.py", line 519, in _handle_workers
15:03:44     cls._wait_for_updates(current_sentinels, change_notifier)
15:03:44   File "/usr/lib64/python3.9/multiprocessing/pool.py", line 499, in _wait_for_updates
15:03:44     wait(sentinels, timeout=timeout)
15:03:44   File "/usr/lib64/python3.9/multiprocessing/connection.py", line 935, in wait
15:03:44     ready = selector.select(timeout)
15:03:44   File "/usr/lib64/python3.9/selectors.py", line 416, in select
15:03:44     fd_event_list = self._selector.poll(timeout)
15:03:44 
15:03:44 ~~~~~~~~~~~~~~~~~~~~ Stack of MainThread (140642209965888) ~~~~~~~~~~~~~~~~~~~~~
15:03:44   File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
15:03:44     return _run_code(code, main_globals, None,
15:03:44   File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
15:03:44     exec(code, run_globals)
15:03:44   File "/usr/lib/python3.9/site-packages/pytest/__main__.py", line 5, in <module>
15:03:44     raise SystemExit(pytest.console_main())
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 185, in console_main
15:03:44     code = main()
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 162, in main
15:03:44     ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
15:03:44     return self._hookexec(self, self.get_hookimpls(), kwargs)
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
15:03:44     return self._inner_hookexec(hook, methods, kwargs)
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
15:03:44     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
15:03:44     res = hook_impl.function(*args)
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/main.py", line 316, in pytest_cmdline_main
15:03:44     return wrap_session(config, _main)
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/main.py", line 269, in wrap_session
15:03:44     session.exitstatus = doit(config, session) or 0
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/main.py", line 323, in _main
15:03:44     config.hook.pytest_runtestloop(session=session)
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
15:03:44     return self._hookexec(self, self.get_hookimpls(), kwargs)
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
15:03:44     return self._inner_hookexec(hook, methods, kwargs)
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
15:03:44     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
15:03:44     res = hook_impl.function(*args)
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/main.py", line 348, in pytest_runtestloop
15:03:44     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
15:03:44     return self._hookexec(self, self.get_hookimpls(), kwargs)
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
15:03:44     return self._inner_hookexec(hook, methods, kwargs)
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
15:03:44     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
15:03:44     res = hook_impl.function(*args)
15:03:44   File "/builddir/build/BUILDROOT/python-pytest-rerunfailures-9.1.1-3.el9.noarch/usr/lib/python3.9/site-packages/pytest_rerunfailures.py", line 240, in pytest_runtest_protocol
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 126, in runtestprotocol
15:03:44     reports.append(call_and_report(item, "call", log))
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 215, in call_and_report
15:03:44     call = call_runtest_hook(item, when, **kwds)
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 254, in call_runtest_hook
15:03:44     return CallInfo.from_call(
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 311, in from_call
15:03:44     result: Optional[TResult] = func()
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 255, in <lambda>
15:03:44     lambda: ihook(item=item, **kwds), when=when, reraise=reraise
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
15:03:44     return self._hookexec(self, self.get_hookimpls(), kwargs)
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
15:03:44     return self._inner_hookexec(hook, methods, kwargs)
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
15:03:44     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
15:03:44     res = hook_impl.function(*args)
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 162, in pytest_runtest_call
15:03:44     item.runtest()
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/python.py", line 1641, in runtest
15:03:44     self.ihook.pytest_pyfunc_call(pyfuncitem=self)
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
15:03:44     return self._hookexec(self, self.get_hookimpls(), kwargs)
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
15:03:44     return self._inner_hookexec(hook, methods, kwargs)
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
15:03:44     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
15:03:44   File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
15:03:44     res = hook_impl.function(*args)
15:03:44   File "/usr/lib/python3.9/site-packages/_pytest/python.py", line 183, in pytest_pyfunc_call
15:03:44     result = testfunction(**testargs)
15:03:44   File "/home/jenkins-agent/workspace/ci_linux-rhel/ws/src/ros2/ros2cli/ros2cli/test/test_flake8.py", line 22, in test_flake8
15:03:44     rc, errors = main_with_errors(argv=[])
15:03:44   File "/home/jenkins-agent/workspace/ci_linux-rhel/ws/install/ament_flake8/lib/python3.9/site-packages/ament_flake8/main.py", line 88, in main_with_errors
15:03:44     report = generate_flake8_report(
15:03:44   File "/home/jenkins-agent/workspace/ci_linux-rhel/ws/install/ament_flake8/lib/python3.9/site-packages/ament_flake8/main.py", line 281, in generate_flake8_report
15:03:44     report.report = style.check_files(paths)
15:03:44   File "/usr/lib/python3.9/site-packages/flake8/api/legacy.py", line 109, in check_files
15:03:44     self._application.run_checks(paths)
15:03:44   File "/usr/lib/python3.9/site-packages/flake8/main/application.py", line 271, in run_checks
15:03:44     self.file_checker_manager.run()
15:03:44   File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 309, in run
15:03:44     self.run_parallel()
15:03:44   File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 275, in run_parallel
15:03:44     for ret in pool_map:
15:03:44   File "/usr/lib64/python3.9/multiprocessing/pool.py", line 448, in <genexpr>
15:03:44     return (item for chunk in result for item in chunk)
15:03:44   File "/usr/lib64/python3.9/multiprocessing/pool.py", line 858, in next
15:03:44     self._cond.wait(timeout)
15:03:44   File "/usr/lib64/python3.9/threading.py", line 312, in wait
15:03:44     waiter.acquire()
```

</details>

we could ask some help for flake8 project with creating issue?

**Comment by sloretz** [comment]
@mergifyio update

**Review by sloretz — APPROVED** [review]

**Comment by sloretz** [comment]
Pulls: https://github.com/ros2/rclpy/pull/1358
Gist: https://gist.githubusercontent.com/sloretz/81ef1fb38810dc80de05afeac3957c63/raw/ed65b256cf0cf0b945f9c10f001041eb86752447/ros2.repos
BUILD args:  --packages-up-to rclpy
TEST args:  --packages-select rclpy
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14739
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22042/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16296/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1559/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22772/)

**Comment by sloretz** [comment]
Thank you for the PR!

**Pull request merged**
