### PR TITLE
[iron] Fix an inherent race in execution vs. destruction. (backport of #1150)

### PR DESCRIPTION
**Pull request by Timple**
Backport of https://github.com/ros2/rclpy/pull/1150

I ran into this and noticed a solution is already available.

Thank you @clalancette for the works!

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]
lgtm

**Comment by fujitatomoya** [comment]
@clalancette what do you think about this backport? i think that is fine, this gives us better user experience. the backport is straight-forward.

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20488/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14890/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21235/)

**Review by clalancette — APPROVED** [review]
I think this is an OK one to backport.  It does change API a bit, but it is deep in the executor, and changes underscore-prefixed methods.

**Pull request merged**
