### PR TITLE
GetTypeDescription service

### PR DESCRIPTION
**Pull request by emersonknapp**
Part of ros2/ros2#1159

Depends on https://github.com/ros2/rcl/pull/1052
Equivalent to https://github.com/ros2/rclcpp/pull/2224
Defines and implements a new component of `rclpy.Node` that initializes and handles requests for the `~/get_type_description` service.

### CODE REVIEW

**Comment by emersonknapp** [comment]
Pulls: ros2/rcl#1052, ros2/rclpy#1139
Gist: https://gist.githubusercontent.com/emersonknapp/0ece934b18cc98956ac8cdb2e4f43683/raw/0edfddf4e6bcc841f51aafbd86d30828149f58d0/ros2.repos
BUILD args:  --packages-above-and-dependencies rclpy
TEST args:  --packages-above rclpy
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/12328
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19077/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13604/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19823/)

**Review by clalancette — COMMENTED** [review]
I have no specific problems with this PR, but it does look like some of the tests are failing.  That will need to be fixed.

**Comment by emersonknapp** [comment]
Pulls: ros2/rcl#1052, ros2/rclpy#1139, ros2/ros2cli#838
Gist: https://gist.githubusercontent.com/emersonknapp/6e2279fa4f0eb0eedbfeb3e35f26ec32/raw/ad52397c613bf02fb10895f6d4df38e03728e848/ros2.repos
BUILD args:  --packages-above-and-dependencies rclpy ros2cli ros2param ros2service
TEST args:  --packages-above rclpy ros2cli ros2param ros2service
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/12332
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19081/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13608/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19827/)

**Comment by emersonknapp** [comment]
Pulls: ros2/rclpy#1139, ros2/ros2cli#838
Gist: https://gist.githubusercontent.com/emersonknapp/b636f6ea5ccf709b1fc5684de991cb07/raw/99521abc39bdfb6dd39d76e87727d54d198a9cce/ros2.repos
BUILD args:  --packages-above-and-dependencies rclpy ros2cli ros2param ros2service
TEST args:  --packages-above rclpy ros2cli ros2param ros2service
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/12334
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19083/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13610/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19829/)

**Comment by emersonknapp** [comment]
Looking for greens, checking for flaky:
* Windows [Build Status](https://ci.ros2.org/job/ci_windows/19835/)

**Comment by emersonknapp** [comment]
Yep, all green. Think we have a flaky test on windows but I feel confident it is unrelated to this changeset

**Comment by clalancette** [comment]
> Yep, all green. Think we have preexisting flaky test on windows, but I feel confident it is unrelated to this changeset

Yeah, that Windows failure is a flake.  This otherwise looks good to me.

**Review by clalancette — APPROVED** [review]

**Pull request merged**
