### PR TITLE
typo fix.

### PR DESCRIPTION
**Pull request by fujitatomoya**
Signed-off-by: Tomoya.Fujita <Tomoya.Fujita@sony.com>

### CODE REVIEW

**Comment by fujitatomoya** [comment]
@clalancette just typo fix, could you help me to merge this?

**Comment by clalancette** [comment]
@ros-pull-request-builder retest this please

**Comment by fujitatomoya** [comment]
@ros-pull-request-builder retest this please

**Comment by clalancette** [comment]
@ros-pull-request-builder retest this please

**Review by clalancette — APPROVED** [review]

**Pull request merged**
