### PR TITLE
claim maintainership

### PR DESCRIPTION
**Pull request by wjwwood**
See: https://github.com/ros2/ros2/issues/519

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Thanks @wjwwood !

Can you please add the author entry under the license so that this still passes the linter?

**Comment by wjwwood** [comment]
I don't understand the rationale for splitting up maintainers and authors, but sure ok :)

**Comment by wjwwood** [comment]
Do I have to do a new release of `rclpy`?

**Comment by mikaelarguedas** [comment]
> I don't understand the rationale for splitting up maintainers and authors, but sure ok :)

Me neither as I was not around when these xsds were created...

> Do I have to do a new release of rclpy?

Yes please :)

**Pull request merged**
