### PR TITLE
Add types to qos_overriding_options.py

### PR DESCRIPTION
**Pull request by InvincibleRMC**

### CODE REVIEW

**Review by sloretz — APPROVED** [review]

**Comment by sloretz** [comment]
CI ([repos file](https://gist.githubusercontent.com/sloretz/ae5cff987bf89035b336a7cc79860bc0/raw/d47b0ae10c00d37e024dcbf51d81ad788d3dac44/ros2.repos) build: `--packages-above-and-dependencies rclpy` test: `--packages-above rclpy`)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20467/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14869/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21210/)

**Comment by fujitatomoya** [comment]
it should be fixed and green CI, starting another try.

CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20486/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14888/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21232/)

**Comment by InvincibleRMC** [comment]
> it should be fixed and green CI, starting another try.
> 
> CI:
> 
> * Linux [Build Status](http://ci.ros2.org/job/ci_linux/20486/)
> * Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14888/)
> * Windows [Build Status](http://ci.ros2.org/job/ci_windows/21232/)

Any idea why libyaml_vendor has been running for over a day?

**Comment by fujitatomoya** [comment]
I have no idea, it just said `libyaml_vendor under processing...`, i just aborted the job and restart windows CI.

* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21236/)

**Comment by InvincibleRMC** [comment]
Now that CI has passed are we waiting on anything to merge this in?

**Comment by fujitatomoya** [comment]
@InvincibleRMC No, this is good to go.

**Pull request merged**
