### PR TITLE
Add useful debug info when trying to publish the wrong type

### PR DESCRIPTION
**Pull request by LoyVanBeek**
I stumbled upon https://stackoverflow.com/questions/62324936/ros2-typeerror-when-publishing-custom-message-to-topic-python the other day and thought: "Should be an easy fix, if you know what you did wrong" and this PR should help with that.

### CODE REVIEW

**Comment by clalancette** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11210/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6483/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9169/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11127/)

**Comment by LoyVanBeek** [comment]
The `Rpr__rclpy__ubuntu_focal_amd64` check fails, but for unrelated reasons it seems:

```
13:40:27 In file included from /tmp/ws/src/rclpy/rclpy/src/rclpy/_rclpy.c:57:
13:40:27 /tmp/ws/src/rclpy/rclpy/src/rclpy/./_rclpy_qos_event.c:23:3: error: unknown type name ‘rmw_message_lost_status_t’
13:40:27    23 |   rmw_message_lost_status_t message_lost;
13:40:27       |   ^~~~~~~~~~~~~~~~~~~~~~~~~
13:40:27 /tmp/ws/src/rclpy/rclpy/src/rclpy/./_rclpy_qos_event.c: In function ‘_message_lost_to_py_object’:
13:40:27 /tmp/ws/src/rclpy/rclpy/src/rclpy/./_rclpy_qos_event.c:171:3: error: unknown type name ‘rmw_message_lost_status_t’; did you mean ‘rmw_liveliness_lost_status_t’?
13:40:27   171 |   rmw_message_lost_status_t * actual_data = &data->message_lost;
13:40:27       |   ^~~~~~~~~~~~~~~~~~~~~~~~~
13:40:27       |   rmw_liveliness_lost_status_t
13:40:27 /tmp/ws/src/rclpy/rclpy/src/rclpy/./_rclpy_qos_event.c:174:16: error: request for member ‘total_count’ in something not a structure or union
13:40:27   174 |     actual_data->total_count,
13:40:27       |                ^~
13:40:27 /tmp/ws/src/rclpy/rclpy/src/rclpy/./_rclpy_qos_event.c:175:16: error: request for member ‘total_count_change’ in something not a structure or union
13:40:27   175 |     actual_data->total_count_change);
13:40:27       |                ^~
13:40:27 /tmp/ws/src/rclpy/rclpy/src/rclpy/./_rclpy_qos_event.c: In function ‘_get_qos_event_data_filler_function_for’:
13:40:27 /tmp/ws/src/rclpy/rclpy/src/rclpy/./_rclpy_qos_event.c:254:12: error: ‘RCL_SUBSCRIPTION_MESSAGE_LOST’ undeclared (first use in this function)
13:40:27   254 |       case RCL_SUBSCRIPTION_MESSAGE_LOST:
13:40:27       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
13:40:27 /tmp/ws/src/rclpy/rclpy/src/rclpy/./_rclpy_qos_event.c:254:12: note: each undeclared identifier is reported only once for each function it appears in
13:40:27 make[2]: *** [CMakeFiles/rclpy.dir/build.make:63: CMakeFiles/rclpy.dir/src/rclpy/_rclpy.c.o] Error 1
13:40:27 make[1]: *** [CMakeFiles/Makefile2:117: CMakeFiles/rclpy.dir/all] Error 2
13:40:27 make: *** [Makefile:141: all] Error 2
```

**Comment by clalancette** [comment]
Yes, I'm not sure what is going on with the Rolling PR build.

But there is actually a warning from the regular CI build.  It looks like a flake8 error:

```
./rclpy/publisher.py:73:22: E271 multiple spaces after keyword
                raise  TypeError('Expected {}, got {}'.format(self.msg_type, type(msg)))
                     ^

1     E271 multiple spaces after keyword

86 files checked
1 errors
```

Can you please fix it up?

**Comment by LoyVanBeek** [comment]
Done

**Comment by clalancette** [comment]
Can you please sign that last commit?  That will make the DCO check pass.  I'll also run CI again, then I think this will be good to go in.  Thanks.

**Comment by clalancette** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11221/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6491/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9180/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11137/)

**Comment by clalancette** [comment]
Sorry, this dropped off of my radar.  CI looks good, there have been no significant changes since CI was last run, so I'll go ahead and merge.  Thanks for the contribution.

**Pull request merged**
