### PR TITLE
default to c11

### PR DESCRIPTION
**Pull request by mikaelarguedas**
follow up of https://github.com/ros2/ros2/issues/362 revived during review of https://github.com/ros2/rclpy/pull/102#discussion_r137089299

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/3231/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/539/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/2575/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3293/)

**Comment by dirk-thomas** [comment]
The new compiler warning seems to indicate that we need C11.

**Comment by mikaelarguedas** [comment]
> The new compiler warning seems to indicate that we need C11.

Indeed.
The question is: if we "require" C11 to build without warnings on MacOS, should we lock down the standard version and not allow users to override it ? Or should we keep the conditional leaving control to the users at their own risks?

**Comment by dirk-thomas** [comment]
Imo we should always allow an external override. A user might have a use case to override it - either with an older or newer version. We shouldn't prevent them from doing it (or require them to modify the sources).

**Comment by mikaelarguedas** [comment]
> Imo we should always allow an external override.

Fair enough https://github.com/ros2/rclpy/pull/118/commits/822298d63ab856d6132600527f850db942909e19

Run a macOS job just to confirm that warnings disappear (even if the warnings were pretty explicit...)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/2576/)

**Pull request merged**
