### PR TITLE
Fixes spin_until_future_complete removing node it didn't add

### PR DESCRIPTION
**Pull request by jmblixt3**
Closes https://github.com/ros2/rclpy/issues/1313
Current if spin_unitl_future_complete is called inside a nodes callback it removes the node from the executor
This results in any subsiquent waitables to never be checked by the node since the node is no longer in the executor
This aims to fix that by only removing the node from the executor if it wasn't already present

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
@jmblixt3 

does this really resolve the https://github.com/ros2/rclpy/issues/1313#issue-2404263314? i think you are using the same callback group, and `rcl_wait` with recursive executor spin. seems pretty much you are hitting the situation described in https://docs.ros.org/en/rolling/How-To-Guides/Using-callback-groups.html#avoiding-deadlocks?

even if that works, waiting on the future completion synchronously in the callback would block the other entities with the same callback group to be blocked, i would not think this is good design practice for the application.

i may be missing something, i would like to get more comments from others.

**Comment by jmblixt3** [comment]
Looking at [rclcpp clcpp/executors.hpp](https://github.com/ros2/rclcpp/blob/647bd65e289c1ed4fbf89f1a151fd21040b940c4/rclcpp/include/rclcpp/executors.hpp#L92), there's a similar TODO to the issue I described. I'm not sure which version of test code you looked at, but this is what I used to validate the issue beforehand, and how to show it was fixed after. Looking at the original issue see the usage of fibonacci_action_server, fibonacci_action_hybrid, and ros2 action send_goal. The last version of the hybrid is below
## fibomnacci_action_hybrid.py
```python3
import rclpy
from rclpy import Future
from rclpy.action import ActionServer, ActionClient
from rclpy.action.client import ClientGoalHandle
from rclpy.action.server import ServerGoalHandle
import rclpy.logging
from rclpy.node import Node

from action_tutorials_interfaces.action import Fibonacci

from rclpy.executors import ExternalShutdownException

class FibonacciActionServer(Node):
    def __init__(self):
        super().__init__("fibonacci_action_server")
        # self.client_node = rclpy.create_node('fibonacci_action_server_client')
        self._action_server = ActionServer(
            self, Fibonacci, "some_action", self.execute_callback
        )
        self._action_client = ActionClient(
            self, Fibonacci, "fibonacci"
        )

    def execute_callback(self, goal_handle: ServerGoalHandle):
        self.get_logger().info("Requesting goal...")
        request_future = self._action_client.send_goal_async(Fibonacci.Goal(order=goal_handle.request.order))
        rclpy.spin_until_future_complete(self,request_future)
        self.get_logger().info("Recieved request result...")
        spin_handle: ClientGoalHandle = request_future.result()
        result_future: Future = spin_handle.get_result_async()
        rclpy.spin_until_future_complete(self,result_future)
        self.get_logger().info("Recieved final result...")
        result = Fibonacci.Result()
        if not result_future.cancelled():
            result = result_future.result().result
        goal_handle.succeed()
        return result



def main(args=None):
    try:
        with rclpy.init(args=args):
            fibonacci_action_server = FibonacciActionServer()
            rclpy.spin(fibonacci_action_server)
    except (KeyboardInterrupt, ExternalShutdownException):
        pass


if __name__ == '__main__':
    main()


```

**Comment by MichaelOrlov** [comment]
@sloretz It seems we did talk about this issue before. Could you please follow up on it and give some comments?

**Review by sloretz — APPROVED** [review]
The fix LGTM, but please use coroutines for waiting for results inside a callback https://github.com/ros2/rclpy/issues/1313#issuecomment-2307615945

**Comment by sloretz** [comment]
@mergifyio update

**Comment by sloretz** [comment]
Pulls: ros2/rclpy#1316
Gist: https://gist.githubusercontent.com/sloretz/450ced2a382151503e56242c22eeccf7/raw/cae0f91ede29d09f58213d1e855db468c8081b45/ros2.repos
BUILD args:  --packages-above-and-dependencies rclpy
TEST args:  --packages-above rclpy
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14465
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21734/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16009/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1240/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22437/)

**Comment by sloretz** [comment]
Thanks for the PR!

**Comment by jmblixt3** [comment]
@sloretz can this be back ported?

**Comment by sloretz** [comment]
@mergifyio backport jazzy iron humble

**Pull request merged**
