### PR TITLE
Add types to Action Server and Action Client

### PR DESCRIPTION
**Pull request by InvincibleRMC**

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]
lgtm with green CI

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclpy#1349
Gist: https://gist.githubusercontent.com/fujitatomoya/d1c28940dae674d54c74566a19bfc13b/raw/8844303445a5a3b903daea42dbae4862b475ffc4/ros2.repos
BUILD args:  --packages-above-and-dependencies rclpy
TEST args:  --packages-above rclpy
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14507
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21782/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16053/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1285/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22481/)

**Comment by InvincibleRMC** [comment]
@fujitatomoya There was an import error. It should be fixed now.

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21791/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16062/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1293/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22489/)

**Comment by InvincibleRMC** [comment]
@fujitatomoya Fixed a bad import for Python3.8 so Windows should now pass.

**Comment by fujitatomoya** [comment]
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1302/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22500/)

**Comment by InvincibleRMC** [comment]
@fujitatomoya is this good to merge?

**Comment by fujitatomoya** [comment]
Last CI unstable warnings are unrelated to this PR.

**Comment by clalancette** [comment]
Just as an FYI, this is probably the cause of https://github.com/ros2/ros2cli/issues/932 .  Since it is so large it is somewhat hard to figure out exactly what is happening, but we'll need to examine it more closely.

**Comment by fujitatomoya** [comment]
@clalancette thanks for checking that. i am okay to revert this fix, are you also going to do that? CC: @InvincibleRMC

**Comment by InvincibleRMC** [comment]
Re-looking at the changes I made nothing seems obvious that would make it seg fault sometimes only on `rhel`. But reverting and splitting into smaller PRs seems wise.

**Comment by fujitatomoya** [comment]
revert PR: https://github.com/ros2/rclpy/pull/1359

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-kilted-kaiju-release/43902/1

**Pull request merged**
