### PR TITLE
avoid lifecycle node transition exception

### PR DESCRIPTION
**Pull request by fujitatomoya**
addresses https://github.com/ros2/rclpy/issues/1209

replaces https://github.com/ros2/rclpy/pull/1317

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
with this fix, we can avoid the crash on action server from exception and the action client can receive the response with failure as below.

```bash
root@tomoyafujita:~/ros2_ws/colcon_ws# ros2 run lifecycle_py lifecycle_talker 
[WARN] [1721693858.103483007] [rcl_lifecycle]: No transition matching 2 found for current state unconfigured
[ERROR] [1721693858.114465029] [lc_talker]: Unable to start transition 2 from current state (1, 'unconfigured')

root@tomoyafujita:~/ros2_ws/colcon_ws# ros2 service call /lc_talker/change_state lifecycle_msgs/srv/ChangeState "{transition: {id: 2}}"
requester: making request: lifecycle_msgs.srv.ChangeState_Request(transition=lifecycle_msgs.msg.Transition(id=2, label=''))

response:
lifecycle_msgs.srv.ChangeState_Response(success=False)
```
```

**Comment by fujitatomoya** [comment]
@mjforan @Barry-Xu-2018 @chrisbitter if any of you can do the review or test, that will be really appreciated.

**Comment by Barry-Xu-2018** [comment]
About __change_state(), my understanding is 
- Before calling this function, the state machine should be in a primary state (unconfigured, inactive, active or finalized). After calling this function, it should switch to another primary state.
- The argument `transition_id` for __change_state() should be one of configure, cleanup, activate, deactivate, unconfigured_shutdown, inactive_shutdown and active_shutdown

So, when returning from __change_state(), we need to ensure that the state machine is in a primary state, not a transition state (such as configuring, cleaningup, shuttingdown, etc).  

Is my understanding correct?

Besides, __change_state() may be executed concurrently (the program modifies the state while an external process modifies the state through `change_state` service).  This function does not have lock protection

**Comment by mjforan** [comment]
Testing the basic `lifecycle_py` demo shows the change properly.
Before:
Screenshot from 2024-08-01 16-16-20
After:
Screenshot from 2024-08-01 16-16-52
I had to use the Rolling branch of `rclpy` because `lifecycle_py` doesn't work under Jazzy.

I agree with @Barry-Xu-2018; the exception should not be handled the same way for all three instances.
My opinion:
|x | exception caused by                                         | how to handle                                           |
|---|---------------------------------------------------------------|--------------------------------------------------------|
|1 | invalid transition request                                 | write to log and return error to caller |
|2 | unable to transition out of transition state  | enter `ErrorProcessing`                          |
|3 | unable to transition out of `ErrorProcessing` | raise an exception and crash              |

**Comment by fujitatomoya** [comment]
@mjcarroll @sloretz @ahcorde can you take a look when you have time?

**Review by ahcorde — APPROVED** [review]

**Review by ahcorde — CHANGES_REQUESTED** [review]
There are some conflict to resolve

**Comment by fujitatomoya** [comment]
@ahcorde appreciate your time for the review, thanks! yeah, i will do rebase and resolve the conflict, and get back to you.

**Comment by fujitatomoya** [comment]
@Barry-Xu-2018 about your comment on https://github.com/ros2/rclpy/pull/1319#issuecomment-2244532000 makes sense. (including locking mechanism) AFAIS, current PR is aligned with `rclcpp` behavior. how about addressing this comment with another issue? this is gonna be more complicated and takes time to verify.

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclpy#1319
Gist: https://gist.githubusercontent.com/fujitatomoya/1d9faa816731c8aee120548004e4bb46/raw/7ea0f998c7e152f14f1d178cf76fa6d108383ba1/ros2.repos
BUILD args:  --packages-above-and-dependencies rclpy
TEST args:  --packages-above rclpy
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14891
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22203/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16457/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1724/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22953/)

**Comment by fujitatomoya** [comment]
@Barry-Xu-2018 friendly ping

**Comment by Barry-Xu-2018** [comment]
LGTM

**Comment by fujitatomoya** [comment]
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1789/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/23040/)

**Comment by fujitatomoya** [comment]
https://ci.ros2.org/job/ci_linux-rhel/1789/#showFailuresLink is unrelated.

**Pull request merged**
