### PR TITLE
Fix Time and Duration raising exception when compared to another type

### LINKED ISSUE #952: rclpy.time.Time and rclpy.duration.Duration raise error on comparing to None
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binaries
- Version or commit hash:
  - ros-foxy-rclpy 1.0.8-1focal.20220209.144341
- Client library:
  - rclpy

#### Steps to reproduce issue

```python
import rclpy.time

t = rclpy.time.Time()
print("t in [None, t]: %r" % (t in [None, t]))
```

```python
import rclpy.duration

d = rclpy.duration.Duration()
print("d in [None, d]: %r" % (d in [None, d]))
```

#### Expected behavior

```
t in [None, t]: True
```
```
d in [None, d]: True
```

#### Actual behavior

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/time.py", line 105, in __eq__
    raise TypeError("Can't compare time with object of type: ", type(other))
TypeError: ("Can't compare time with object of type: ", <class 'NoneType'>)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/duration.py", line 44, in __eq__
    raise TypeError("Can't compare duration with object of type: ", type(other))
TypeError: ("Can't compare duration with object of type: ", <class 'NoneType'>)
```

#### Additional information

Not specific to Foxy: present in all versions of ROS2.

### PR DESCRIPTION
**Pull request by suurjaak**
Fixes #952.

Ought to be back-ported to Galactic and Foxy as well.

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]
lgtm, @sloretz can you take a look?

**Comment by fujitatomoya** [comment]
Note, original issue detected on Foxy, we need to backport all supported ROS 2 distribution (humble, galactic and foxy)

**Comment by suurjaak** [comment]
@fujitatomoya @sloretz ping on this?

**Comment by clalancette** [comment]
> Note, original issue detected on Foxy, we need to backport all supported ROS 2 distribution (humble, galactic and foxy)

I don't think we should backport this.  This is a behavior change, and I don't think we should do that in the already released distributions.  For rolling, this is fine.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18229/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12760/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18898/)

**Comment by suurjaak** [comment]
> This is a behavior change, and I don't think we should do that in the already released distributions.

I would say that this is a bugfix, and as such ought to be ported to distros being supported.

**Comment by clalancette** [comment]
> I would say that this is a bugfix, and as such ought to be ported to distros being supported.

But it is a potentially major behavior change, and has the ability to break things that already work.  A good indication that this is the case is the fact that we needed to change tests to deal with this.

This is OK for Rolling (and distros going forward), it is not acceptable for already released distributions.  So I am still not in favor of backporting this.

**Comment by fujitatomoya** [comment]
IMO, i totally understand your point. this kind of policy should be simple as much as possible, once we have exception that will be hard to keep afterwards. So i am still not positive to backport this.

**Comment by suurjaak** [comment]
Well, regardless of which version this gets ported to, how about getting this merged?

**Comment by fujitatomoya** [comment]
@suurjaak thanks for the contribution, the issue has been also closed accordingly.

**Comment by suurjaak** [comment]
@clalancette I can do the release note PR as well.

**Comment by clalancette** [comment]
> @clalancette I can do the release note PR as well.

Thank you, it is much appreciated!

**Pull request merged**
