### PR TITLE
Utilities.py types.

### PR DESCRIPTION
**Pull request by InvincibleRMC**
Add types to utilities.py and started `rclpyHandle`. Built off of #1240.

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
I merged the `rolling` branch here.  With that, this looks good.  I'll run CI next.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21582/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15871/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1080/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22302/)

**Comment by InvincibleRMC** [comment]
Sure

**Comment by clalancette** [comment]
New CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21584/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15873/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1083/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22304/)

**Review by fujitatomoya — APPROVED** [review]

**Pull request merged**
