### PR TITLE
Missing exception states in rclpy

### PR DESCRIPTION
**Pull request by hemantku**
#224

### CODE REVIEW

**Comment by sloretz** [comment]
I agree with @wjwwood that exceptions should be added with code raising them. Without that I'm not sure if any given exception will be necessary.

**Comment by hemantku** [comment]
I have used these exceptions in the joint_state_publisher package which I migrated to ROS 2. I would be happy to include this along with appropriate CR's for initiate and shutdown as they are made

**Comment by wjwwood** [comment]
@hemantku how are you using these exceptions in `joint_state_publisher`? are you just `try-except`'ing them or are you throwing them yourself?

**Comment by hemantku** [comment]
@wjwwood  Try-except'ing them

**Comment by wjwwood** [comment]
Well, if nothing is raising them then why do you need to try-except them? 😄

**Comment by wjwwood** [comment]
Are you trying to have one Python file that supports ROS 1 and ROS 2 maybe?

If not, then I'd really say let's leave this pr (perhaps close it but leave the branch/fork) and reintroduce the exceptions when they're being used.

It's also possible that there are already functions which _should_ raise them already but are not. In which case updating this pr to replace existing `RuntimeError` raises with more specific exceptions would be acceptable as well.

**Comment by hemantku** [comment]
Alright, I will close this PR out and introduce them along when I replace the RuntimeError

**Pull request closed without merging**
